### ISSUE TITLE
ECONNREFUSED error doesn't trigger timeout

### ISSUE THREAD

**Issue by ogdenstudios** [rbren/rss-parser#145]
Love the package and it's really made my life easier. Thanks for all your work! 

I've got an application that parses thousands of RSS feeds. I've chopped it up into lambda functions and for the most part, everything is working smoothly. 

However, I've noticed some weird behavior around the timeout function. I instantiate rss-parser like so: 

```
const Parser = require('rss-parser');
const parser = new Parser({
  timeout: 2000,
});
```

And set a timeout on it for 2000 ms. 

Then I run something like: 

```
const rss = await parser.parseURL(feed.url);
```

For the most part, that timeout works. Slow responses or rejected responses time out and give me a timeout error. 

But every now and then, I hit a feed that doesn't timeout for a long, long time. In some instances, it seems to sit in the event loop infinitely. It causes my functions to hang entirely. When I run them in lambda, the function times out based on how much time I configure it to use (I've tried up to 2 minutes). 

When I run it locally, something different happens. I usually get a timeout around 10 seconds or so. And the error I get looks like this; 

```
{ Error: connect ECONNREFUSED 198.238.208.213:80
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1107:14)
  errno: 'ECONNREFUSED',
  code: 'ECONNREFUSED',
  syscall: 'connect',
  address: '198.238.208.213',
  port: 80 }
```

This is the response when I run it against [http://rss.leg.wa.gov/BillSummary/Home/Rss/2334/2017/House](http://rss.leg.wa.gov/BillSummary/Home/Rss/2334/2017/House). 

Is there something in particular about this kind of connection error that isn't triggering the timeout? I wonder if this is related to #122. 

Let me know if you need any more info here. I'd love to help troubleshoot this or better understand what I've missed.

**Comment by rbren** [comment]
We pass the timeout option to the node HTTP library. That happens here: https://github.com/rbren/rss-parser/blob/55f947ee18ab14896ec284cc784efeb25e59c628/lib/parser.js#L103

Curious if the issue is in that library, or in our usage of it.

We could handle the timeout separately in this library as well. Happy to accept a PR here.

**Comment by ogdenstudios** [comment]
Awesome! I'll take a look and push something up this week. Thank you!

**Comment by madwings** [comment]
The fix suggested is a nasty hack. The client library itself should not do such things.
ECONNREFUSED is error on the library itself and the on('error') method should catch it. If the setTimeout and on('error') on the library is not working properly the user should report the env he is working with because it could be a bug of node version. And implement this simple fix on his end not messing with the suggested way the request library is working. Such timeout may result in unreleased resources such as network handles. We do not not how setTimeout works on its end.

**Comment by rbren** [comment]
I disagree that it's a "nasty hack". It makes sense that the timeout should respond to things like XML parsing etc, so having our own timeout, rather than relying on the HTTP library, makes sense to me.

We're also not killing the request logic in any way, just calling `Promise.reject`, so unreleased resources shouldn't be a problem.

That said, I agree that filing an issue against the node HTTP library would be a good thing to do.
