### ISSUE TITLE
Incorrect date in isoDate field

### ISSUE THREAD

**Issue by Kelanor** [rbren/rss-parser#156]
Some rss feeds has custom date format, e.x.:
* `20-04-2020 19:00 +0400`
* `14-04-2020 19:00 +0400`
* `10-04-2020 19:00 +0400`

where format looks like `DD-MM-YYYY HH:mm Z`.

But parser just parse this date strings with Date object (in ISO or RFC standard) which looks confusing in output data. We have 4th Oct 2020 instead of 10th Apr 2020.

I suggest to rework this parsing, e.x. using moment with strict utc parsing.
`moment.utc('date', moment.ISO_8601, true)`
`moment.utc('date', moment.RFC_2822, true)`

**Comment by rbren** [comment]
Thanks for reaching out!

RSS specifies that dates [must be in RFC 822 format](https://stackoverflow.com/questions/11993258/what-is-the-correct-format-for-rss-feed-pubdate). We also don't want to include `moment` in order to keep down package size.

However, I'd accept a PR that adds an option for different date parsing strategies using native JS.
